### PR TITLE
[Ambassador] Rick Davies

### PR DESCRIPTION
**Pull request by pietbrauer**

### CODE REVIEW

**Comment by rickydazla** [comment]
@pietbrauer :cherries::cherries::cherries:

sweeeet! thanks

Since it's in the 1st person some minor changes if you don't mind? Also an actual pic of me!

```
I work on Github every day and have developed a small internal app that publishes merged pull requests directly to Shopify. It allows me to develop for Shopify on iOS using Git2Go. This has been my dream forever. Reviewing code from my dev team, merging and publishing from anywhere (the beach, the bar!)

Until I discovered Git2Go I struggled with mobile editors. It's easy to integrate Textastic via the document provider, which lets me make changes effortlessly using an editor that supports over 80 languages. The integration really shines in split view on my iPad Pro as I can commit code without leaving the editor.
```

rickportrait

**Comment by pietbrauer** [comment]
Perfect, will integrate it tomorrow! Thanks a ton!

**Comment by pietbrauer** [comment]
Hey @rickydazla, I integrated your changes (only remove the beach bar thingy 😉). Thanks a lot for the photo. Let me know if you have any other improvements!

**Comment by rickydazla** [comment]
Looks good to me man. I actually did do some coding at the beach bar today! :tropical_drink::palm_tree::surfer:

**Comment by pietbrauer** [comment]
Sweet, me too, almost at the beach (Ubud). It's just because it is mainly to attract lead engineers or engineering lead of big corps I don't know if they find that as cool as we do 😀

**Pull request merged**
